leaf
milena-kos/cat-bot pull request #34
Opened 2023-06-21 08:51 UTC by ZakChrom

🍁

2023-06-21 08:54 UTC, milena-kos requested changes

2023-06-21 08:54 UTC, milena-kos commented on main.py
> +    if "leafbot" in message.author.name.lower() and "hmm... i would rate catbot" in message.content.lower():
```suggestion
    if "leafbot" in message.author.name.lower() and "hmm... i would rate cat" in message.content.lower():
```

2023-06-21 08:55 UTC, milena-kos commented
uwunerd

2023-06-21 08:55 UTC, milena-kos commented
owo i can do that

2023-06-21 08:56 UTC, milena-kos approved these changes
thumb up

2023-06-21 08:56 UTC, merged

2023-06-22 12:11 UTC, Floppy4 commented
![image](https://github.com/milena-kos/cat-bot/assets/123978215/eecbf8c8-b15f-47a9-b30d-46039f0451e4)

2023-06-22 13:37 UTC, milena-kos commented
that is, indeed, what this pr added
thanks for demonstrative imagery